### LIST

#GET ENFERmEIRO
GET http://localhost:3030/unidades/

### CREATE
POST http://localhost:3030/unidades
Content-Type: application/json

{
  "name": "Enfermeiro",
  "unidade": "pitangui",
  "horario": "TERÇA"
}

### UPDATE
PATCH http://localhost:3000/unidades

### DELETE
DELETE http://localhost:3000/unidades